### ISSUE TITLE
placement fails on iCeCube2

### ISSUE THREAD

**Issue by 2015mp** [cliffordwolf/picorv32#36] opened 2017-03-12 02:10 UTC
When i run picorv32 with icecube2, it fails with the error below in placer (windows).  I suspect its a multiple assignment issue on decoder_trigger, and decoder_pseudo_trigger, or synplify optimizing that bit away due to the 
decoder_pseudo_trigger <= 0;
assignment .   I'll try to get a sim going, to debug this more.

Design Statistics after Packing
    Number of LUTs      	:	1545
    Number of DFFs      	:	608
    Number of DFFs packed to IO	:	0
    Number of Carrys    	:	233
Device Utilization Summary after Packing
    Sequential LogicCells
        LUT and DFF      	:	502
        LUT, DFF and CARRY	:	106
    Combinational LogicCells
        Only LUT         	:	872
        CARRY Only       	:	62
        LUT with CARRY   	:	65
    LogicCells                  :	1607/7680
    PLBs                        :	211/960
    BRAMs                       :	8/32
    IOs and GBIOs               :	9/206
    PLLs                        :	0/2
I2088: Phase 3, elapsed time : 2.3 (sec)
Phase 4
I2712: Tool unable to find location for GB cpu.decoder_trigger_RNIV293 
Error during global Buffer placement

**Comment by cliffordwolf** [comment] 2017-03-12 10:22
> I suspect its a multiple assignment issue on decoder_trigger, and decoder_pseudo_trigger

There is no multiple assignment issue with either of that signals. (They are both assigned to in only one always block.) If you think you found a problem, be more specific!

I've run synthesis and placement using scripts/icestorm/example.v as top module with iCEcube2 2017.01 and it runs through without any problems.

Unfortunately you don't specify which icecube version you are using, what your top-level design is, or provide any other useful information I could possibly use to reproduce the issue.

So I'm closing this issue because of lack of useful information to work with. If you are serious, please consider opening a serious issue, i.e. one containing enough information to actually reproduce the problem.

**Closed by cliffordwolf** 2017-03-12 10:22 UTC
